DO $legacy_users$
BEGIN
  IF pg_catalog.to_regclass('public.users') IS NOT NULL THEN
    EXECUTE 'ALTER TABLE public.users ENABLE ROW LEVEL SECURITY';
    EXECUTE 'REVOKE ALL ON TABLE public.users FROM PUBLIC, anon, authenticated';
  END IF;
END;
$legacy_users$;

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  display_name text NOT NULL
    CHECK (char_length(btrim(display_name)) BETWEEN 1 AND 100),
  username text NOT NULL UNIQUE
    CHECK (username ~ '^[a-z0-9_]{3,32}$'),
  role text NOT NULL DEFAULT 'user'
    CHECK (role IN ('admin', 'kasir', 'user')),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL
    CHECK (char_length(btrim(nama)) BETWEEN 1 AND 200),
  harga bigint NOT NULL
    CHECK (harga BETWEEN 0 AND 999999999999),
  stok integer NOT NULL DEFAULT 0
    CHECK (stok BETWEEN 0 AND 2147483647),
  kategori text NOT NULL DEFAULT 'Umum'
    CHECK (char_length(btrim(kategori)) BETWEEN 1 AND 100),
  foto_url text
    CHECK (
      foto_url IS NULL OR
      (char_length(foto_url) <= 2048 AND foto_url ~* '^https://')
    ),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cashier_id uuid NOT NULL REFERENCES public.profiles (id) ON DELETE RESTRICT,
  total_amount bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  payment_method text NOT NULL DEFAULT 'cash',
  paid_amount bigint NOT NULL DEFAULT 0,
  change_amount bigint NOT NULL DEFAULT 0,
  CONSTRAINT sales_payment_method_valid
    CHECK (payment_method IN ('cash', 'qris', 'other')),
  CONSTRAINT sales_total_amount_safe_range
    CHECK (total_amount BETWEEN 0 AND 9007199254740991),
  CONSTRAINT sales_paid_amount_covers_total
    CHECK (paid_amount >= total_amount),
  CONSTRAINT sales_paid_amount_safe_range
    CHECK (paid_amount <= 9007199254740991),
  CONSTRAINT sales_change_matches_amounts
    CHECK (change_amount = paid_amount - total_amount),
  CONSTRAINT sales_non_cash_exact_amount
    CHECK (payment_method = 'cash' OR paid_amount = total_amount)
);

ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS payment_method text NOT NULL DEFAULT 'cash',
  ADD COLUMN IF NOT EXISTS paid_amount bigint NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS change_amount bigint NOT NULL DEFAULT 0;

UPDATE public.sales
SET paid_amount = total_amount,
    change_amount = 0
WHERE paid_amount < total_amount;

ALTER TABLE public.sales
  ALTER COLUMN payment_method DROP DEFAULT,
  ALTER COLUMN paid_amount DROP DEFAULT,
  ALTER COLUMN change_amount DROP DEFAULT;

DO $constraints$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_payment_method_valid'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_payment_method_valid
      CHECK (payment_method IN ('cash', 'qris', 'other'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_total_amount_safe_range'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_total_amount_safe_range
      CHECK (total_amount BETWEEN 0 AND 9007199254740991);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_paid_amount_covers_total'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_paid_amount_covers_total
      CHECK (paid_amount >= total_amount);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_paid_amount_safe_range'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_paid_amount_safe_range
      CHECK (paid_amount <= 9007199254740991);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_change_matches_amounts'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_change_matches_amounts
      CHECK (change_amount = paid_amount - total_amount);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.sales'::regclass
      AND conname = 'sales_non_cash_exact_amount'
  ) THEN
    ALTER TABLE public.sales
      ADD CONSTRAINT sales_non_cash_exact_amount
      CHECK (payment_method = 'cash' OR paid_amount = total_amount);
  END IF;
END;
$constraints$;

CREATE TABLE IF NOT EXISTS public.sale_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id bigint NOT NULL REFERENCES public.sales (id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products (id) ON DELETE RESTRICT,
  nama_produk text NOT NULL
    CHECK (char_length(btrim(nama_produk)) BETWEEN 1 AND 200),
  quantity integer NOT NULL CHECK (quantity BETWEEN 1 AND 100000),
  unit_price bigint NOT NULL CHECK (unit_price BETWEEN 0 AND 999999999999),
  line_total bigint NOT NULL CHECK (line_total >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sale_items_line_total_matches
    CHECK (line_total = quantity::bigint * unit_price)
);

CREATE INDEX IF NOT EXISTS products_created_at_idx
  ON public.products (created_at DESC);
CREATE INDEX IF NOT EXISTS products_kategori_idx
  ON public.products (kategori);
CREATE INDEX IF NOT EXISTS sales_cashier_created_at_idx
  ON public.sales (cashier_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sale_items_sale_id_idx
  ON public.sale_items (sale_id);
CREATE INDEX IF NOT EXISTS sale_items_product_id_idx
  ON public.sale_items (product_id);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog
AS $function$
BEGIN
  NEW.updated_at := pg_catalog.now();
  RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS profiles_set_updated_at ON public.profiles;
CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS products_set_updated_at ON public.products;
CREATE TRIGGER products_set_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- Helper is SECURITY DEFINER to avoid recursive profile RLS checks. The path
-- is fixed and all application objects are schema-qualified.
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles AS p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
      AND p.is_active
  );
$function$;

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

CREATE OR REPLACE FUNCTION public.admin_deactivate_profile(
  p_target_user_id uuid
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $function$
DECLARE
  v_role text;
  v_is_active boolean;
  v_active_admins bigint;
BEGIN
  IF auth.role() IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION 'Service role required' USING ERRCODE = '42501';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(74321091, 1);

  SELECT p.role, p.is_active
  INTO v_role, v_is_active
  FROM public.profiles AS p
  WHERE p.id = p_target_user_id
  FOR UPDATE;

  IF NOT FOUND OR NOT v_is_active THEN
    RAISE EXCEPTION 'Active user profile not found' USING ERRCODE = 'P0002';
  END IF;

  IF v_role = 'admin' THEN
    SELECT count(*)
    INTO v_active_admins
    FROM public.profiles AS p
    WHERE p.role = 'admin'
      AND p.is_active;

    IF v_active_admins <= 1 THEN
      RAISE EXCEPTION 'Cannot deactivate the last active admin'
        USING ERRCODE = '23514';
    END IF;
  END IF;

  UPDATE public.profiles
  SET is_active = false
  WHERE id = p_target_user_id;
END;
$function$;

REVOKE ALL ON FUNCTION public.admin_deactivate_profile(uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_deactivate_profile(uuid) TO service_role;

-- Create a profile for each Auth account. Auth metadata can supply a display
-- name/username, but can never grant a privileged role.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $function$
DECLARE
  v_display_name text;
  v_username text;
  v_fallback_username text;
BEGIN
  v_display_name := left(
    coalesce(
      nullif(btrim(NEW.raw_user_meta_data ->> 'display_name'), ''),
      nullif(btrim(NEW.raw_user_meta_data ->> 'full_name'), ''),
      nullif(btrim(split_part(coalesce(NEW.email, ''), '@', 1)), ''),
      'Pengguna'
    ),
    100
  );

  v_username := lower(
    regexp_replace(
      coalesce(
        NEW.raw_user_meta_data ->> 'username',
        split_part(coalesce(NEW.email, ''), '@', 1),
        ''
      ),
      '[^a-zA-Z0-9_]',
      '_',
      'g'
    )
  );
  v_username := left(trim(both '_' FROM v_username), 32);
  IF char_length(v_username) < 3 THEN
    v_username := 'user';
  END IF;

  INSERT INTO public.profiles (id, display_name, username, role)
  VALUES (NEW.id, v_display_name, v_username, 'user')
  ON CONFLICT (id) DO NOTHING;

  RETURN NEW;
EXCEPTION
  WHEN unique_violation THEN
    -- A duplicate requested username gets a deterministic, UUID-derived name.
    -- The suffix is server-generated, not taken from user metadata.
    v_fallback_username :=
      'u_' || left(replace(NEW.id::text, '-', ''), 30);
    INSERT INTO public.profiles (id, display_name, username, role)
    VALUES (NEW.id, v_display_name, v_fallback_username, 'user')
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$function$;

REVOKE ALL ON FUNCTION public.handle_new_auth_user()
  FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_auth_user();

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;

-- Explicit grants are paired with RLS. Anonymous visitors may only read the
-- public product catalog; all other application data requires authentication.
REVOKE ALL ON public.profiles, public.products, public.sales, public.sale_items
  FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.profiles TO authenticated;
GRANT SELECT ON public.products TO anon;
GRANT UPDATE (role) ON public.profiles TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON public.products, public.sales, public.sale_items
  TO authenticated;

DO $drop_pos_policies$
DECLARE
  policy_row record;
BEGIN
  FOR policy_row IN
    SELECT schemaname, tablename, policyname
    FROM pg_catalog.pg_policies
    WHERE schemaname = 'public'
      AND tablename IN ('profiles', 'products', 'sales', 'sale_items')
  LOOP
    EXECUTE pg_catalog.format(
      'DROP POLICY %I ON %I.%I',
      policy_row.policyname,
      policy_row.schemaname,
      policy_row.tablename
    );
  END LOOP;
END;
$drop_pos_policies$;

DROP POLICY IF EXISTS "Profiles are visible to self and admins" ON public.profiles;
CREATE POLICY "Profiles are visible to self and admins"
  ON public.profiles FOR SELECT TO authenticated
  USING (id = (SELECT auth.uid()) OR (SELECT public.is_admin()));

DROP POLICY IF EXISTS "Admins manage profiles" ON public.profiles;
DROP POLICY IF EXISTS "Admins update profiles" ON public.profiles;
CREATE POLICY "Admins update profiles"
  ON public.profiles FOR UPDATE TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK (
    (SELECT public.is_admin())
    AND (id <> (SELECT auth.uid()) OR role = 'admin')
  );

DROP POLICY IF EXISTS "Authenticated users read products" ON public.products;
CREATE POLICY "Authenticated users read products"
  ON public.products FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Public can read products" ON public.products;
CREATE POLICY "Public can read products"
  ON public.products FOR SELECT TO anon
  USING (true);

DROP POLICY IF EXISTS "Admins manage products" ON public.products;
CREATE POLICY "Admins manage products"
  ON public.products FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

DROP POLICY IF EXISTS "Users read their own sales" ON public.sales;
CREATE POLICY "Users read their own sales"
  ON public.sales FOR SELECT TO authenticated
  USING (
    cashier_id = (SELECT auth.uid())
    AND EXISTS (
      SELECT 1 FROM public.profiles AS p
      WHERE p.id = (SELECT auth.uid()) AND p.is_active
    )
  );

DROP POLICY IF EXISTS "Admins manage all sales" ON public.sales;
CREATE POLICY "Admins manage all sales"
  ON public.sales FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

DROP POLICY IF EXISTS "Users read items from their own sales" ON public.sale_items;
CREATE POLICY "Users read items from their own sales"
  ON public.sale_items FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.sales AS s
      WHERE s.id = sale_items.sale_id
        AND s.cashier_id = (SELECT auth.uid())
        AND EXISTS (
          SELECT 1 FROM public.profiles AS p
          WHERE p.id = (SELECT auth.uid()) AND p.is_active
        )
    )
  );

DROP POLICY IF EXISTS "Admins manage all sale items" ON public.sale_items;
CREATE POLICY "Admins manage all sale items"
  ON public.sale_items FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

-- Atomic checkout. Item input is a JSON array of objects with numeric
-- product_id and quantity fields. Duplicate product rows are consolidated.
-- Products are locked in ascending ID order to avoid checkout deadlocks.
DROP FUNCTION IF EXISTS public.checkout(jsonb);

CREATE OR REPLACE FUNCTION public.checkout(
  p_items jsonb,
  p_payment_method text,
  p_paid_amount bigint
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog
AS $function$
DECLARE
  v_user_id uuid;
  v_role text;
  v_item record;
  v_price bigint;
  v_stock integer;
  v_total numeric := 0;
  v_change numeric;
  v_sale_id bigint;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501';
  END IF;

  SELECT p.role
  INTO v_role
  FROM public.profiles AS p
  WHERE p.id = v_user_id
    AND p.is_active;

  IF v_role IS DISTINCT FROM 'kasir' THEN
    RAISE EXCEPTION 'Only cashier accounts may check out'
      USING ERRCODE = '42501';
  END IF;

  IF p_payment_method IS NULL OR p_payment_method NOT IN ('cash', 'qris', 'other') THEN
    RAISE EXCEPTION 'Unsupported payment method'
      USING ERRCODE = '22023';
  END IF;

  IF p_paid_amount IS NULL OR p_paid_amount < 0 THEN
    RAISE EXCEPTION 'Paid amount must be zero or greater'
      USING ERRCODE = '22023';
  END IF;

  IF p_items IS NULL OR jsonb_typeof(p_items) IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'Checkout requires between 1 and 100 item rows'
      USING ERRCODE = '22023';
  END IF;

  IF jsonb_array_length(p_items) NOT BETWEEN 1 AND 100 THEN
    RAISE EXCEPTION 'Checkout requires between 1 and 100 item rows'
      USING ERRCODE = '22023';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_items) AS item(value)
    WHERE jsonb_typeof(item.value) IS DISTINCT FROM 'object'
       OR jsonb_typeof(item.value -> 'product_id') IS DISTINCT FROM 'number'
       OR jsonb_typeof(item.value -> 'quantity') IS DISTINCT FROM 'number'
       OR coalesce(item.value ->> 'product_id', '') !~ '^[1-9][0-9]{0,18}$'
       OR coalesce(item.value ->> 'quantity', '') !~ '^[1-9][0-9]{0,5}$'
       OR CASE
            WHEN coalesce(item.value ->> 'quantity', '') ~ '^[1-9][0-9]{0,5}$'
              THEN (item.value ->> 'quantity')::numeric > 100000
            ELSE false
          END
       OR CASE
            WHEN coalesce(item.value ->> 'product_id', '') ~ '^[1-9][0-9]{0,18}$'
              THEN (item.value ->> 'product_id')::numeric > 9223372036854775807
            ELSE false
          END
  ) THEN
    RAISE EXCEPTION 'Each checkout row must have a valid product_id and quantity'
      USING ERRCODE = '22023';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM (
      SELECT (item.value ->> 'product_id')::bigint AS product_id,
             sum((item.value ->> 'quantity')::integer) AS quantity
      FROM jsonb_array_elements(p_items) AS item(value)
      GROUP BY (item.value ->> 'product_id')::bigint
    ) AS requested
    WHERE requested.quantity > 100000
  ) THEN
    RAISE EXCEPTION 'Combined quantity for a product exceeds the limit'
      USING ERRCODE = '22023';
  END IF;

  -- Lock and validate all products before writing any sale data.
  FOR v_item IN
    SELECT (item.value ->> 'product_id')::bigint AS product_id,
           sum((item.value ->> 'quantity')::integer)::integer AS quantity
    FROM jsonb_array_elements(p_items) AS item(value)
    GROUP BY (item.value ->> 'product_id')::bigint
    ORDER BY (item.value ->> 'product_id')::bigint
  LOOP
    SELECT p.harga, p.stok
    INTO v_price, v_stock
    FROM public.products AS p
    WHERE p.id = v_item.product_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Product % was not found', v_item.product_id
        USING ERRCODE = 'P0002';
    END IF;

    IF v_stock < v_item.quantity THEN
      RAISE EXCEPTION 'Insufficient stock for product %', v_item.product_id
        USING ERRCODE = '22000';
    END IF;

    v_total := v_total + (v_price::numeric * v_item.quantity::numeric);
  END LOOP;

  IF v_total > 9007199254740991 THEN
    RAISE EXCEPTION 'Sale total exceeds the supported amount'
      USING ERRCODE = '22003';
  END IF;
  IF p_paid_amount > 9007199254740991 THEN
    RAISE EXCEPTION 'Paid amount exceeds the supported amount'
      USING ERRCODE = '22003';
  END IF;

  IF p_payment_method = 'cash' AND p_paid_amount::numeric < v_total THEN
    RAISE EXCEPTION 'Cash received is less than the sale total'
      USING ERRCODE = '22023';
  END IF;
  IF p_payment_method <> 'cash' AND p_paid_amount::numeric <> v_total THEN
    RAISE EXCEPTION 'Non-cash payment must match the sale total'
      USING ERRCODE = '22023';
  END IF;

  v_change := p_paid_amount::numeric - v_total;
  INSERT INTO public.sales (
    cashier_id, total_amount, payment_method, paid_amount, change_amount
  )
  VALUES (
    v_user_id, v_total::bigint, p_payment_method, p_paid_amount, v_change::bigint
  )
  RETURNING id INTO v_sale_id;

  FOR v_item IN
    SELECT (item.value ->> 'product_id')::bigint AS product_id,
           sum((item.value ->> 'quantity')::integer)::integer AS quantity
    FROM jsonb_array_elements(p_items) AS item(value)
    GROUP BY (item.value ->> 'product_id')::bigint
    ORDER BY (item.value ->> 'product_id')::bigint
  LOOP
    INSERT INTO public.sale_items (
      sale_id, product_id, nama_produk, quantity, unit_price, line_total
    )
    SELECT v_sale_id,
           p.id,
           p.nama,
           v_item.quantity,
           p.harga,
           (p.harga::numeric * v_item.quantity::numeric)::bigint
    FROM public.products AS p
    WHERE p.id = v_item.product_id;

    UPDATE public.products AS p
    SET stok = p.stok - v_item.quantity,
        updated_at = now()
    WHERE p.id = v_item.product_id;
  END LOOP;

  RETURN v_sale_id;
END;
$function$;

REVOKE ALL ON FUNCTION public.checkout(jsonb, text, bigint)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.checkout(jsonb, text, bigint) TO authenticated;

-- Product images are publicly readable, while only admins may upload,
-- replace, or delete objects. Re-running updates this bucket's intended
-- visibility and upload constraints without deleting stored files.
INSERT INTO storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
)
VALUES (
  'produk-foto',
  'produk-foto',
  true,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']::text[]
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DO $drop_product_photo_policies$
DECLARE
  policy_row record;
BEGIN
  FOR policy_row IN
    SELECT policyname
    FROM pg_catalog.pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND (
        coalesce(qual, '') ILIKE '%produk-foto%'
        OR coalesce(with_check, '') ILIKE '%produk-foto%'
      )
  LOOP
    EXECUTE pg_catalog.format(
      'DROP POLICY %I ON storage.objects',
      policy_row.policyname
    );
  END LOOP;
END;
$drop_product_photo_policies$;

DROP POLICY IF EXISTS "Public can read product photos" ON storage.objects;
CREATE POLICY "Public can read product photos"
  ON storage.objects FOR SELECT TO public
  USING (bucket_id = 'produk-foto');

DROP POLICY IF EXISTS "Admins upload product photos" ON storage.objects;
CREATE POLICY "Admins upload product photos"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'produk-foto'
    AND (SELECT public.is_admin())
  );

DROP POLICY IF EXISTS "Admins update product photos" ON storage.objects;
CREATE POLICY "Admins update product photos"
  ON storage.objects FOR UPDATE TO authenticated
  USING (
    bucket_id = 'produk-foto'
    AND (SELECT public.is_admin())
  )
  WITH CHECK (
    bucket_id = 'produk-foto'
    AND (SELECT public.is_admin())
  );

DROP POLICY IF EXISTS "Admins delete product photos" ON storage.objects;
CREATE POLICY "Admins delete product photos"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'produk-foto'
    AND (SELECT public.is_admin())
  );
